package kuroyale.domain;

public enum QuestType {
    WIN_MATCHES,
    DESTROY_CROWN_TOWERS,
    PLAY_SPELL_CARDS,
    DEPLOY_TROOP_CARDS,
    SPEND_ELIXIR,
    WIN_WITHOUT_LOSING_CROWN,
    PLAY_BUILDING_CARDS,
    DEAL_SPELL_DAMAGE,
    WIN_ONLY_COMMON,
    COMPLETE_CHALLENGES,
    WIN_NETWORK_MATCH,
    PLAY_20_CARDS_SINGLE_MATCH,
    WIN_STREAK,
    DESTROY_ENEMY_KING,
    WIN_PVP_MATCH
}

